-- ******************************* SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: commercial_aviation , v16 vs v12 by jerdavies@gmail.com *

ALTER TABLE CORE.BOOKING
    ADD COLUMN BAG_COUNT integer DEFAULT 0 NOT NULL COMMENT 'Number of bags associated with a booking for a particular passenger';