-- ******************************* SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: commercial_aviation , v17 vs v16 by jerdavies@gmail.com *

ALTER TABLE CORE.BOOKING
    ALTER COLUMN BAG_COUNT COMMENT 'Bag count for passenger associated with this booking';