-- ******************************* SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: commercial_aviation , v18 vs uat by jerdavies@gmail.com *

ALTER TABLE CORE.FLIGHT_SCHEDULE
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.ROUTE
    DROP CONSTRAINT FK_2;

ALTER TABLE CORE.ROUTE
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.ROUTE
    DROP CONSTRAINT FK_4;

ALTER TABLE CORE.ROUTE
    DROP CONSTRAINT FK_3;

ALTER TABLE CORE.BOOKING
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.AIRPORT
    DROP CONSTRAINT FK_3;

ALTER TABLE CORE.FLIGHT
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.FLIGHT
    DROP CONSTRAINT FK_2;

ALTER TABLE CORE.FLIGHT
    DROP CONSTRAINT FK_6;

ALTER TABLE CORE.FLIGHT
    DROP CONSTRAINT FK_3;

ALTER TABLE CORE.PASSENGER
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.GATE
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.AIRCAFT
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.TICKET
    DROP CONSTRAINT FK_1;

ALTER TABLE CORE.AIRLINE
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.FLIGHT_SCHEDULE
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.COUNTRY
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.ROUTE
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.BOOKING
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.AIRPORT
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.FLIGHT
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.PASSENGER
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.AIRCAFT
    DROP CONSTRAINT PK_1;

ALTER TABLE CORE.TICKET
    DROP CONSTRAINT PK_1;

ALTER TABLE AIRLINE
    DROP COLUMN AIRLINE_ID;

ALTER TABLE CORE.AIRLINE
    ADD COLUMN AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry';

ALTER TABLE FLIGHT_SCHEDULE
    DROP COLUMN FLIGHT_SCHEDULE_ID;

ALTER TABLE FLIGHT_SCHEDULE
    DROP COLUMN ROUTE_ID;

ALTER TABLE CORE.FLIGHT_SCHEDULE
    ADD COLUMN FLIGHT_SCHEDULE_ID integer NOT NULL COMMENT 'Unique identifier for a specific flight schedule entry, used to track and reference individual flight schedule records in the database';

ALTER TABLE CORE.FLIGHT_SCHEDULE
    ADD COLUMN ROUTE_ID integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.';

ALTER TABLE COUNTRY
    DROP COLUMN COUNTRY_ID;

ALTER TABLE CORE.COUNTRY
    ADD COLUMN COUNTRY_ID integer NOT NULL COMMENT 'Unique identifier for each country in the database, used to uniquely reference and distinguish different countries within the table or across related tables';

ALTER TABLE ROUTE
    DROP COLUMN AIRCRAFT_ID;

ALTER TABLE ROUTE
    DROP COLUMN DEPARTURE_AIRPORT_ID;

ALTER TABLE ROUTE
    DROP COLUMN AIRLINE_ID;

ALTER TABLE ROUTE
    DROP COLUMN ROUTE_ID;

ALTER TABLE ROUTE
    DROP COLUMN ARRIVAL_AIRPORT_ID;

ALTER TABLE CORE.ROUTE
    ADD COLUMN AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry';

ALTER TABLE CORE.ROUTE
    ADD COLUMN AIRCRAFT_ID integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.';

ALTER TABLE CORE.ROUTE
    ADD COLUMN ARRIVAL_AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for the airport where the flight or transportation unit arrives. This column likely contains airport codes (such as IATA or ICAO codes) that uniquely represent the destination airport in the transportation or flight tracking system.';

ALTER TABLE CORE.ROUTE
    ADD COLUMN DEPARTURE_AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for the airport from which the flight departs. This alphanumeric code represents the specific airport of origin for a flight, typically using standardized airport codes (such as IATA or ICAO codes) to precisely locate the departure point.';

ALTER TABLE CORE.ROUTE
    ADD COLUMN ROUTE_ID integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.';

ALTER TABLE BOOKING
    DROP COLUMN BAG_COUNT;

ALTER TABLE BOOKING
    DROP COLUMN PASSENGER_ID;

ALTER TABLE BOOKING
    DROP COLUMN BOOKING_ID;

ALTER TABLE CORE.BOOKING
    ADD COLUMN BOOKING_ID integer NOT NULL COMMENT 'Unique identifier for each booking transaction, used to track and reference individual bookings within the system. This alphanumeric code helps in uniquely identifying and managing specific booking records.';

ALTER TABLE CORE.BOOKING
    ADD COLUMN BAG_COUNT integer DEFAULT 0 NOT NULL COMMENT 'Bag count for passenger associated with this booking';

ALTER TABLE CORE.BOOKING
    ADD COLUMN PASSENGER_ID integer NOT NULL COMMENT 'Unique identifier assigned to each passenger in the dataset, used to distinctly track and reference individual travelers within the system or record.';

ALTER TABLE AIRPORT
    DROP COLUMN AIRPORT_ID;

ALTER TABLE AIRPORT
    DROP COLUMN COUNTRY_ID;

ALTER TABLE CORE.AIRPORT
    ADD COLUMN AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for an airport, typically a code that uniquely represents a specific airport location within a database or transportation system.';

ALTER TABLE CORE.AIRPORT
    ADD COLUMN COUNTRY_ID integer NOT NULL COMMENT 'Unique identifier for each country in the database, serving as the primary key to uniquely distinguish and reference individual countries within the table.';

ALTER TABLE FLIGHT
    DROP COLUMN FLIGHT_DETAIL_ID;

ALTER TABLE FLIGHT
    DROP COLUMN ROUTE_ID;

ALTER TABLE FLIGHT
    DROP COLUMN TICKET_ID;

ALTER TABLE FLIGHT
    DROP COLUMN AIRCRAFT_ID;

ALTER TABLE FLIGHT
    DROP COLUMN FLIGHT_SCHEDULE_ID;

ALTER TABLE CORE.FLIGHT
    ADD COLUMN AIRCRAFT_ID integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.';

ALTER TABLE CORE.FLIGHT
    ADD COLUMN ROUTE_ID integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.';

ALTER TABLE CORE.FLIGHT
    ADD COLUMN FLIGHT_DETAIL_ID integer NOT NULL COMMENT 'Unique identifier for a specific flight detail record, used to uniquely track and reference individual flight information within the database table';

ALTER TABLE CORE.FLIGHT
    ADD COLUMN FLIGHT_SCHEDULE_ID integer NOT NULL COMMENT 'Unique identifier for a specific flight schedule entry, used to track and reference individual flight schedules within the system. This column helps in uniquely identifying and managing different flight schedule records.';

ALTER TABLE CORE.FLIGHT
    ADD COLUMN TICKET_ID integer NOT NULL;

ALTER TABLE PASSENGER
    DROP COLUMN PASSENGER_ID;

ALTER TABLE PASSENGER
    DROP COLUMN COUNTRY_ID;

ALTER TABLE PASSENGER
    DROP COLUMN PASSPORT_NUMBER;

ALTER TABLE CORE.PASSENGER
    ADD COLUMN PASSPORT_NUMBER integer NOT NULL COMMENT 'A unique identifier assigned to an individual''s passport, typically consisting of a series of alphanumeric characters used for international travel and personal identification purposes.';

ALTER TABLE CORE.PASSENGER
    ADD COLUMN PASSENGER_ID integer NOT NULL COMMENT 'Unique identifier assigned to each passenger in the dataset, used to distinguish and track individual passengers across different records or analyses';

ALTER TABLE CORE.PASSENGER
    ADD COLUMN COUNTRY_ID integer NOT NULL COMMENT 'Unique identifier for each country in the database, used to uniquely reference and distinguish different countries within the table or across related tables';

ALTER TABLE GATE
    DROP COLUMN AIRLINE_ID;

ALTER TABLE GATE
    DROP COLUMN AIRPORT_ID;

ALTER TABLE CORE.GATE
    ADD COLUMN AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry';

ALTER TABLE CORE.GATE
    ADD COLUMN AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for an airport, typically a code that uniquely represents a specific airport location within a database or transportation system.';

ALTER TABLE AIRCAFT
    DROP COLUMN AIRCRAFT_ID;

ALTER TABLE AIRCAFT
    DROP COLUMN AIRLINE_ID;

ALTER TABLE CORE.AIRCAFT
    ADD COLUMN AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to each airline in the database, typically used to uniquely distinguish and reference specific airlines across different records or tables.';

ALTER TABLE CORE.AIRCAFT
    ADD COLUMN AIRCRAFT_ID integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.';

ALTER TABLE TICKET
    DROP COLUMN BOOKING_ID;

ALTER TABLE TICKET
    DROP COLUMN TICKET_ID;

ALTER TABLE CORE.TICKET
    ADD COLUMN TICKET_ID integer NOT NULL COMMENT 'Unique identifier for each ticket in the system, typically used to track and reference individual support or service requests uniquely';

ALTER TABLE CORE.TICKET
    ADD COLUMN BOOKING_ID integer NOT NULL COMMENT 'Unique identifier for each booking record, used to track and distinguish individual bookings within the system. This alphanumeric code serves as a primary key for referencing specific booking transactions.';

ALTER TABLE CORE.AIRLINE
    ADD CONSTRAINT PK_1 PRIMARY KEY ( AIRLINE_ID );

ALTER TABLE CORE.FLIGHT_SCHEDULE
    ADD CONSTRAINT PK_1 PRIMARY KEY ( FLIGHT_SCHEDULE_ID );

ALTER TABLE CORE.COUNTRY
    ADD CONSTRAINT PK_1 PRIMARY KEY ( COUNTRY_ID );

ALTER TABLE CORE.ROUTE
    ADD CONSTRAINT PK_1 PRIMARY KEY ( ROUTE_ID );

ALTER TABLE CORE.BOOKING
    ADD CONSTRAINT PK_1 PRIMARY KEY ( BOOKING_ID );

ALTER TABLE CORE.AIRPORT
    ADD CONSTRAINT PK_1 PRIMARY KEY ( AIRPORT_ID );

ALTER TABLE CORE.FLIGHT
    ADD CONSTRAINT PK_1 PRIMARY KEY ( FLIGHT_DETAIL_ID );

ALTER TABLE CORE.PASSENGER
    ADD CONSTRAINT PK_1 PRIMARY KEY ( PASSENGER_ID );

ALTER TABLE CORE.AIRCAFT
    ADD CONSTRAINT PK_1 PRIMARY KEY ( AIRCRAFT_ID );

ALTER TABLE CORE.TICKET
    ADD CONSTRAINT PK_1 PRIMARY KEY ( TICKET_ID );

ALTER TABLE CORE.FLIGHT_SCHEDULE
    ADD CONSTRAINT FK_1 FOREIGN KEY ( ROUTE_ID ) REFERENCES CORE.ROUTE ( ROUTE_ID );

ALTER TABLE CORE.ROUTE
    ADD CONSTRAINT FK_4 FOREIGN KEY ( ARRIVAL_AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID );

ALTER TABLE CORE.ROUTE
    ADD CONSTRAINT FK_3 FOREIGN KEY ( DEPARTURE_AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID );

ALTER TABLE CORE.ROUTE
    ADD CONSTRAINT FK_2 FOREIGN KEY ( AIRCRAFT_ID ) REFERENCES CORE.AIRCAFT ( AIRCRAFT_ID );

ALTER TABLE CORE.ROUTE
    ADD CONSTRAINT FK_1 FOREIGN KEY ( AIRLINE_ID ) REFERENCES CORE.AIRLINE ( AIRLINE_ID );

ALTER TABLE CORE.BOOKING
    ADD CONSTRAINT FK_1 FOREIGN KEY ( PASSENGER_ID ) REFERENCES CORE.PASSENGER ( PASSENGER_ID );

ALTER TABLE CORE.AIRPORT
    ADD CONSTRAINT FK_3 FOREIGN KEY ( COUNTRY_ID ) REFERENCES CORE.COUNTRY ( COUNTRY_ID );

ALTER TABLE CORE.FLIGHT
    ADD CONSTRAINT FK_1 FOREIGN KEY ( FLIGHT_SCHEDULE_ID ) REFERENCES CORE.FLIGHT_SCHEDULE ( FLIGHT_SCHEDULE_ID );

ALTER TABLE CORE.FLIGHT
    ADD CONSTRAINT FK_2 FOREIGN KEY ( ROUTE_ID ) REFERENCES CORE.ROUTE ( ROUTE_ID );

ALTER TABLE CORE.FLIGHT
    ADD CONSTRAINT FK_3 FOREIGN KEY ( AIRCRAFT_ID ) REFERENCES CORE.AIRCAFT ( AIRCRAFT_ID );

ALTER TABLE CORE.FLIGHT
    ADD CONSTRAINT FK_6 FOREIGN KEY ( TICKET_ID ) REFERENCES CORE.TICKET ( TICKET_ID );

ALTER TABLE CORE.PASSENGER
    ADD CONSTRAINT FK_1 FOREIGN KEY ( COUNTRY_ID ) REFERENCES CORE.COUNTRY ( COUNTRY_ID );

ALTER TABLE CORE.GATE
    ADD CONSTRAINT FK_1 FOREIGN KEY ( AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID );

ALTER TABLE CORE.AIRCAFT
    ADD CONSTRAINT FK_1 FOREIGN KEY ( AIRLINE_ID ) REFERENCES CORE.AIRLINE ( AIRLINE_ID );

ALTER TABLE CORE.TICKET
    ADD CONSTRAINT FK_1 FOREIGN KEY ( BOOKING_ID ) REFERENCES CORE.BOOKING ( BOOKING_ID );