-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.FLIGHT_SCHEDULE
CREATE OR REPLACE TABLE CORE.FLIGHT_SCHEDULE
(
 FLIGHT_SCHEDULE_ID integer NOT NULL COMMENT 'Unique identifier for a specific flight schedule entry, used to track and reference individual flight schedule records in the database',
 FLIGHT_NUMBER      varchar(16777216) NOT NULL COMMENT 'Unique identifier for a specific flight, typically consisting of an airline code and a sequential or random number that distinguishes this particular flight from others. The Flight Number helps in tracking, booking, and referencing individual flights in airline and travel systems.',
 DEPARTURE_TIME     timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the planned or scheduled time of departure for a specific event or transportation service, representing the exact moment when a vehicle, flight, or other mode of transportation is expected to leave its origin point',
 ARRIVAL_DATE       timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the planned or scheduled arrival time for a specific event, flight, transportation, or delivery',
 ROUTE_ID           integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.',

 CONSTRAINT PK_1 PRIMARY KEY ( FLIGHT_SCHEDULE_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( ROUTE_ID ) REFERENCES CORE.ROUTE ( ROUTE_ID )
)
COMMENT = 'A comprehensive table tracking flight schedules, including details such as flight numbers, departure and arrival times, routes, aircraft information, and operational status for airlines and airport management.';
