-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.GATE
CREATE OR REPLACE TABLE CORE.GATE
(
 GATE_ID    varchar(16777216) NOT NULL COMMENT 'Unique identifier for a specific gate at the airport (within a specific terminal)',
 AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry',
 TERMINAL   varchar(16777216) NOT NULL COMMENT 'A terminal representing a specific zone in an airport, for exsmple Terminal 3 or South Terminal. These tend to be more common in larger, internastional airports.',
 AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for an airport, typically a code that uniquely represents a specific airport location within a database or transportation system.',

 CONSTRAINT PK_1 PRIMARY KEY ( GATE_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID )
)
COMMENT = 'A gate is a sphysical location at an airport and is usually given a num eric identifiertr';
