-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.AIRCAFT
CREATE OR REPLACE TABLE CORE.AIRCAFT
(
 AIRCRAFT_ID         integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.',
 REGISTRATION_NUMBER varchar(16777216) NOT NULL COMMENT 'A unique identifier assigned to an entity during its registration process, typically used for official tracking and identification purposes. This number serves as a distinct reference code that helps in uniquely distinguishing and documenting the specific record within the system.',
 MODEL_TYPE          varchar(16777216) NOT NULL COMMENT 'Identifies the specific type or category of model represented in the dataset, which could include variations like machine learning models, statistical models, predictive models, or classification models used in the analysis or research.',
 MODEL_VARIANT       varchar(16777216) NOT NULL COMMENT 'Identifies the specific configuration or trim level of a vehicle model, representing the unique combination of features, equipment, and specifications within a particular vehicle line',
 MANUFACTURER        varchar(16777216) NOT NULL COMMENT 'The Manufacturer column identifies the company or brand that produced the product or item in the table. It provides information about the origin and creator of the specific item, which can be useful for tracking product lineage, quality assessment, or filtering and analyzing data based on different manufacturers.',
 AIRLINE_ID          integer NOT NULL COMMENT 'Unique identifier assigned to each airline in the database, typically used to uniquely distinguish and reference specific airlines across different records or tables.',

 CONSTRAINT PK_1 PRIMARY KEY ( AIRCRAFT_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( AIRLINE_ID ) REFERENCES CORE.AIRLINE ( AIRLINE_ID )
)
COMMENT = 'A table that stores comprehensive information about aircraft, including details such as aircraft model, manufacturer, registration number, type, capacity, operational status, and other relevant technical and identification attributes used for tracking and managing aviation assets.';
