-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.PASSENGER
CREATE OR REPLACE TABLE CORE.PASSENGER
(
 PASSENGER_ID    integer NOT NULL COMMENT 'Unique identifier assigned to each passenger in the dataset, used to distinguish and track individual passengers across different records or analyses',
 FIRST_NAME      varchar(16777216) NOT NULL COMMENT 'A personal identifier representing an individual''s first name, typically used to capture the initial or given name of a person in a database or record system.',
 LAST_NAME       varchar(16777216) NOT NULL COMMENT 'Last Name column storing the surname or family name of an individual in the database table. Typically contains the family or inherited name of a person, used for identification and sorting purposes.',
 PASSPORT_NUMBER integer NOT NULL COMMENT 'A unique identifier assigned to an individual''s passport, typically consisting of a series of alphanumeric characters used for international travel and personal identification purposes.',
 COUNTRY_ID      integer NOT NULL COMMENT 'Unique identifier for each country in the database, used to uniquely reference and distinguish different countries within the table or across related tables',

 CONSTRAINT PK_1 PRIMARY KEY ( PASSENGER_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( COUNTRY_ID ) REFERENCES CORE.COUNTRY ( COUNTRY_ID )
)
COMMENT = 'Representing passengers in a transportation system, storing essential information about individuals who travel, including personal details, contact information, and potential additional attributes related to their travel profile.';
