-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.AIRPORT
CREATE OR REPLACE TABLE CORE.AIRPORT
(
 AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for an airport, typically a code that uniquely represents a specific airport location within a database or transportation system.',
 NAME       varchar(16777216) NOT NULL COMMENT 'Represents the unique name identifier for an entity in the table with ID 8c0c29b3-f090-4252-9d25-db526aa73f06, typically used to provide a human-readable label or title for the specific record.',
 LATITUDE   number(38,0) NOT NULL COMMENT 'Geographic coordinate representing the north-south position of a point on the Earth''s surface, measured in degrees from the equator (positive values indicate north of the equator, negative values indicate south of the equator).',
 LONGITUDE  number(38,0) NOT NULL COMMENT 'Geographic coordinate representing the east-west position on the Earth''s surface, measured in degrees from the prime meridian. Negative values indicate western longitude, while positive values indicate eastern longitude.',
 ELEVATION  number(38,0) NOT NULL COMMENT 'Represents the height above sea level for a specific geographic location, typically measured in meters or feet. This column provides the vertical distance from a reference point (usually mean sea level) to the ground surface of the given location.',
 COUNTRY_ID integer NOT NULL COMMENT 'Unique identifier for each country in the database, serving as the primary key to uniquely distinguish and reference individual countries within the table.',

 CONSTRAINT PK_1 PRIMARY KEY ( AIRPORT_ID ),
 CONSTRAINT FK_3 FOREIGN KEY ( COUNTRY_ID ) REFERENCES CORE.COUNTRY ( COUNTRY_ID )
)
COMMENT = 'A table representing airports, containing essential information about airport locations, identifiers, and basic characteristics. This table likely includes fields such as airport code, name, city, country, geographic coordinates (latitude and longitude), and potentially additional details like airport type, elevation, and operational status.';
