-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.ROUTE
CREATE OR REPLACE TABLE CORE.ROUTE
(
 ROUTE_ID             integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.',
 ROUTE_NAME           varchar(16777216) NOT NULL COMMENT 'Represents the unique name or identifier for a specific route or pathway in the transportation or navigation system. This column captures the descriptive title given to a particular route, which could be used for easy reference and identification of different travel paths.',
 AIRLINE_ID           integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry',
 AIRCRAFT_ID          integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.',
 DEPARTURE_AIRPORT_ID integer NOT NULL COMMENT 'Unique identifier for the airport from which the flight departs. This alphanumeric code represents the specific airport of origin for a flight, typically using standardized airport codes (such as IATA or ICAO codes) to precisely locate the departure point.',
 ARRIVAL_AIRPORT_ID   integer NOT NULL COMMENT 'Unique identifier for the airport where the flight or transportation unit arrives. This column likely contains airport codes (such as IATA or ICAO codes) that uniquely represent the destination airport in the transportation or flight tracking system.',

 CONSTRAINT PK_1 PRIMARY KEY ( ROUTE_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( AIRLINE_ID ) REFERENCES CORE.AIRLINE ( AIRLINE_ID ),
 CONSTRAINT FK_2 FOREIGN KEY ( AIRCRAFT_ID ) REFERENCES CORE.AIRCAFT ( AIRCRAFT_ID ),
 CONSTRAINT FK_3 FOREIGN KEY ( DEPARTURE_AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID ),
 CONSTRAINT FK_4 FOREIGN KEY ( ARRIVAL_AIRPORT_ID ) REFERENCES CORE.AIRPORT ( AIRPORT_ID )
)
COMMENT = 'A Route represents a specific travel path or transportation connection between two or more locations, typically used in mapping, navigation, or transportation systems. It includes details about the origin, destination, distance, mode of transportation, and potentially intermediate waypoints or stops along the journey.';
