-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.COUNTRY
CREATE OR REPLACE TABLE CORE.COUNTRY
(
 COUNTRY_ID       integer NOT NULL COMMENT 'Unique identifier for each country in the database, used to uniquely reference and distinguish different countries within the table or across related tables',
 NAME             varchar(16777216) NOT NULL COMMENT 'Name column representing the unique identifier or title for an entry in the table, typically used to provide a human-readable label or reference for the specific record.',
 COUNTRY_ISO_CODE varchar(16777216) NOT NULL COMMENT 'A standardized two or three-letter code representing a specific country according to international standards (such as ISO 3166-1 alpha-2 or alpha-3), used for uniquely identifying and categorizing countries in databases, geographic systems, and international communications.',

 CONSTRAINT PK_1 PRIMARY KEY ( COUNTRY_ID )
)
COMMENT = 'A comprehensive table storing information about countries, including their unique identifiers, names, geographical details, and other relevant attributes used for global reference and classification in database systems.';
