-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.FLIGHT
CREATE OR REPLACE TABLE CORE.FLIGHT
(
 FLIGHT_DETAIL_ID    integer NOT NULL COMMENT 'Unique identifier for a specific flight detail record, used to uniquely track and reference individual flight information within the database table',
 ACTUAL_ARRIVED_AT   timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the actual time when an aircraft arrived at its destination, used to track precise arrival timing and potentially compare against expected or scheduled arrival times.',
 ACTUAL_DEPARTURE_AT timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the actual time when a departure occurred, representing the precise moment the aircraft left its original location',
 CREATED_AT          timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating when the record was initially created in the system, representing the exact date and time of the record''s first entry',
 UPDATED_AT          timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the last modification time of the record, automatically updated when any changes are made to the entity',
 FLIGHT_STATUS       varchar(16777216) NOT NULL COMMENT 'Indicates the current condition or state of a flight, such as on-time, delayed, cancelled, departed, arrived, or in-progress. This column provides real-time or historical status information about the flight''s operational condition.',
 CANCELLATION_REASON varchar(16777216) NOT NULL COMMENT 'Indicates the specific reason why a reservation, booking, or service was cancelled by the customer or the service provider. This column captures the underlying cause for the cancellation, which can help in understanding customer behavior, improving service quality, and identifying potential issues in the booking or cancellation process.',
 ROUTE_ID            integer NOT NULL COMMENT 'Unique identifier for a specific transportation route, used to distinctly label and track individual routes within a transportation system or network.',
 AIRCRAFT_ID         integer NOT NULL COMMENT 'Unique identifier assigned to each individual aircraft in the database, used to distinctly track and reference specific aircraft across various records and operations.',
 FLIGHT_SCHEDULE_ID  integer NOT NULL COMMENT 'Unique identifier for a specific flight schedule entry, used to track and reference individual flight schedules within the system. This column helps in uniquely identifying and managing different flight schedule records.',
 GATE_ID             varchar(16777216) NOT NULL COMMENT 'Unique identifier for the specific airport gate where an arriving flight will land and passengers will disembark',
 GATE_ID_1           varchar(16777216) NOT NULL COMMENT 'Unique identifier for the departure gate from which an aircraft is scheduled to depart, used to track and manage gate assignments in an airport terminal',
 TICKET_ID           integer NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( FLIGHT_DETAIL_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( FLIGHT_SCHEDULE_ID ) REFERENCES CORE.FLIGHT_SCHEDULE ( FLIGHT_SCHEDULE_ID ),
 CONSTRAINT FK_2 FOREIGN KEY ( ROUTE_ID ) REFERENCES CORE.ROUTE ( ROUTE_ID ),
 CONSTRAINT FK_3 FOREIGN KEY ( AIRCRAFT_ID ) REFERENCES CORE.AIRCAFT ( AIRCRAFT_ID ),
 CONSTRAINT FK_4 FOREIGN KEY ( GATE_ID_1 ) REFERENCES CORE.GATE ( GATE_ID ),
 CONSTRAINT FK_5 FOREIGN KEY ( GATE_ID ) REFERENCES CORE.GATE ( GATE_ID ),
 CONSTRAINT FK_6 FOREIGN KEY ( TICKET_ID ) REFERENCES CORE.TICKET ( TICKET_ID )
)
COMMENT = 'A Flight table represents detailed information about airline transportation, including flight identifiers, routing, scheduling, aircraft details, and passenger-related information. It typically captures essential data such as flight number, departure and arrival locations, scheduled and actual times, aircraft type, flight status, and other relevant operational parameters for tracking and managing air travel.';
