-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.TICKET
CREATE OR REPLACE TABLE CORE.TICKET
(
 TICKET_ID            integer NOT NULL COMMENT 'Unique identifier for each ticket in the system, typically used to track and reference individual support or service requests uniquely',
 BOOKING_ID           integer NOT NULL COMMENT 'Unique identifier for each booking record, used to track and distinguish individual bookings within the system. This alphanumeric code serves as a primary key for referencing specific booking transactions.',
 CREATE_AT            timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating when the record was initially created in the database, automatically set when the record is first inserted',
 UPDATED_AT           timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the most recent update or modification date for this record in the table, automatically updated when any changes are made to the record.',
 BOARDING_PASS_ISSUED boolean NOT NULL COMMENT 'Indicates whether a boarding pass has been issued for a specific travel record, typically representing the status of check-in and boarding documentation for a passenger',

 CONSTRAINT PK_1 PRIMARY KEY ( TICKET_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( BOOKING_ID ) REFERENCES CORE.BOOKING ( BOOKING_ID )
)
COMMENT = 'Unique identifier for each ticket in the system, used to track and reference individual support or service requests uniquely. This ID helps in organizing, sorting, and quickly locating specific tickets within the customer support or service management workflow.';
