-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.BOOKING
CREATE OR REPLACE TABLE CORE.BOOKING
(
 BOOKING_ID       integer NOT NULL COMMENT 'Unique identifier for each booking transaction, used to track and reference individual bookings within the system. This alphanumeric code helps in uniquely identifying and managing specific booking records.',
 PASSENGER_ID     integer NOT NULL COMMENT 'Unique identifier assigned to each passenger in the dataset, used to distinctly track and reference individual travelers within the system or record.',
 TOTAL_AMOUNT     number(38,0) NOT NULL COMMENT 'The total monetary amount representing the complete sum of all financial transactions or line items in the given record or entry. This column aggregates all costs, charges, or values associated with the specific transaction or data point.',
 BOOKING_CURRENCY varchar(3) NOT NULL COMMENT 'A standardized code representing the specific currency used in financial transactions or reporting for this table''s records. Typically follows international standards like ISO 4217, which provides unique three-letter alphabetic codes for currencies worldwide (e.g., USD for US Dollar, EUR for Euro, GBP for British Pound).',
 CREATED_AT       timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the exact date and time when the record was initially created in the system, used for tracking the origin point of the entry',
 UPDATED_AT       timestamp_ntz(9) NOT NULL COMMENT 'Timestamp indicating the most recent date and time when the record was last updated or modified in the system',

 CONSTRAINT PK_1 PRIMARY KEY ( BOOKING_ID ),
 CONSTRAINT FK_1 FOREIGN KEY ( PASSENGER_ID ) REFERENCES CORE.PASSENGER ( PASSENGER_ID )
)
COMMENT = 'A table that stores booking information, capturing details of reservations or appointments made by customers. It likely includes key fields such as booking ID, customer details, service or item being booked, date and time of booking, status of the reservation, and any additional notes or special requirements.';
