-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: commercial_aviation by jerdavies@gmail.com **

-- ************************************** CORE.AIRLINE
CREATE OR REPLACE TABLE CORE.AIRLINE
(
 AIRLINE_ID integer NOT NULL COMMENT 'Unique identifier assigned to an airline in the database, used to distinctly represent and reference each specific airline entry',
 NAME       varchar(16777216) NOT NULL COMMENT 'Represents the unique name for the Airline',

 CONSTRAINT PK_1 PRIMARY KEY ( AIRLINE_ID )
)
COMMENT = 'A table that stores comprehensive information about airlines, including their unique identifiers, names, country of origin, hub locations, founding year, and operational details such as fleet size, primary routes, and contact information.';
